# yaml-language-server: $schema=http://json-schema.org/draft-07/schema#
dir: internal/generated/mocks
pkgname: mocks
all: true
packages:
  avito_pvz/internal/domain:
    config:
      recursive: true
      filename: domain.go
